'use client'

import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowRight, BatteryCharging, Check, ChevronDown, ChevronLeft, ChevronRight, CloudSun, Globe2, Link2, Menu, MessageCircle, Minus, Play, Plus, Sun, Wrench, X, Zap } from 'lucide-react'
import companyConfig from '@/lib/config'

const heroImage = 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=2200&q=90'
const canadaImage = 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2200&q=90'
const ctaImage = 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=2200&q=90'

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <div className={`reveal ${className}`}>{children}</div>
}
function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`eyebrow ${light ? 'text-[#EE9A2E]' : 'text-[#2E7A57]'}`}>{children}</p> }
function ButtonLink({ children, href = '#contact', dark = false }: { children: React.ReactNode; href?: string; dark?: boolean }) { return <a href={href} className={`button-link ${dark ? 'button-dark' : ''}`}>{children}<ArrowRight aria-hidden="true" /></a> }

function Navbar() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const links = [['Home', '#home'], ['Solar Solutions', '#solutions'], ['Residential', '#solutions'], ['Commercial', '#solutions'], ['How It Works', '#how-it-works'], ['About Us', '#about'], ['FAQs', '#faq']]
  return <header className={`site-nav ${scrolled ? 'site-nav-scrolled' : ''}`}><a className="brand" href="#home" aria-label="[COMPANY NAME] home"><span className="brand-mark"><Sun /></span><span>[COMPANY NAME]</span></a><nav className="desktop-nav">{links.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav><ButtonLink>Get a Free Quote</ButtonLink><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X /> : <Menu />}</button>{open && <div className="mobile-menu"><div className="mobile-menu-inner">{links.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}<ArrowRight /></a>)}<ButtonLink>Get a Free Quote</ButtonLink></div></div>}</header>
}

function Hero() { return <section id="home" className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(14,26,43,.9) 0%, rgba(14,26,43,.58) 46%, rgba(14,26,43,.1) 100%), url(${heroImage})` }}><div className="container hero-content"><Reveal><Eyebrow light>Canadian solar energy solutions</Eyebrow><h1>Power your home with <em>smarter</em> solar energy.</h1><p className="hero-copy">Make a considered investment in your property, your energy future, and a cleaner Canada.</p><div className="hero-actions"><ButtonLink>Get a Free Solar Assessment</ButtonLink><a className="text-link" href="#solutions">Explore Solar Solutions <ArrowDownRight /></a></div><div className="trust-checks">{['Free Consultation', 'Professional Installation', 'Quality Equipment', 'Built for Canadian Conditions'].map(x => <span key={x}><Check />{x}</span>)}</div></Reveal></div><a href="#trust" className="scroll-cue"><span>Scroll to explore</span><ArrowDownRight /></a></section> }

function TrustBar() { return <section id="trust" className="trust-bar"><div className="container stats-row">{companyConfig.stats.map(stat => <Reveal key={stat.label}><div className="stat"><strong>{stat.value}<small>{stat.suffix}</small></strong><span>{stat.label}</span></div></Reveal>)}</div></section> }

const benefitIcons = [Zap, BatteryCharging, CloudSun, Sun]
function WhySolar() { const benefits = ['Lower Energy Costs', 'Greater Energy Independence', 'Cleaner Energy', 'Long-Term Value']; return <section id="about" className="section"><div className="container split-layout"><Reveal className="image-frame"><img src="https://images.unsplash.com/photo-1558449033-6cf3f7f5d7bd?auto=format&fit=crop&w=1300&q=85" alt="Solar panels installed on a modern Canadian home"/><span className="image-note">Designed for the way you live</span></Reveal><Reveal><Eyebrow>Why go solar</Eyebrow><h2>Turn sunlight into long-term energy savings.</h2><p className="lead">Solar is more than a panel on your roof. It is a practical way to take a more active role in your energy story.</p><div className="benefit-grid">{benefits.map((b, i) => { const Icon = benefitIcons[i]; return <div className="benefit-card" key={b}><Icon /><h3>{b}</h3><p>Thoughtful design, measurable value, and a system made for your property.</p></div> })}</div></Reveal></div></section> }

function Solutions() { return <section id="solutions" className="section section-alt"><div className="container"><Reveal><div className="section-heading"><div><Eyebrow>Our solutions</Eyebrow><h2>Energy, thoughtfully engineered.</h2></div><p>From the first conversation to years of support, we make the shift to solar feel clear and considered.</p></div></Reveal><div className="solutions-grid">{companyConfig.services.map((service, i) => <Reveal key={service.title}><article className="solution-card"><div className="card-image"><img src={service.image} alt={`${service.title} solar energy solution`} /><span>0{i + 1}</span></div><div className="card-body"><Eyebrow>{service.category}</Eyebrow><h3>{service.title}</h3><p>{service.description}</p><a href="#contact">{service.ctaLabel}<ArrowRight /></a></div></article></Reveal>)}</div></div></section> }

function HowItWorks() { const steps = [['Consultation', 'We listen to your goals, property, and questions.'], ['Solar Assessment', 'We look at the details that shape your opportunity.'], ['System Design & Installation', 'A considered plan becomes a professional installation.'], ['Start Generating', 'Begin producing energy and track your next chapter.']]; return <section id="how-it-works" className="section process-section"><div className="container"><Reveal><Eyebrow>How it works</Eyebrow><h2>From first question to first ray.</h2></Reveal><div className="process-grid">{steps.map(([title, text], i) => <Reveal key={title}><div className="process-step"><span className="step-number">0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></div></Reveal>)}</div></div></section> }

function CanadaSection() { return <section className="canada-section" style={{ backgroundImage: `linear-gradient(90deg, rgba(14,26,43,.94), rgba(14,26,43,.6)), url(${canadaImage})` }}><div className="container canada-content"><Reveal><Eyebrow light>Made for this place</Eyebrow><h2>Solar built for Canadian conditions.</h2><p>Practical systems, professional installation, and support that understands the seasons.</p><div className="canada-list">{['Seasonal weather considered in design', 'Professional installation from start to finish', 'Quality equipment selected for your property', 'Systems designed around the way your home works', 'Local support when you need it'].map(x => <span key={x}><Check />{x}</span>)}</div></Reveal></div></section> }

function Projects() { const [filter, setFilter] = useState<'All' | 'Residential' | 'Commercial'>('All'); const projects = companyConfig.projects.filter(p => filter === 'All' || p.type === filter); return <section className="section" id="projects"><div className="container"><Reveal><div className="section-heading"><div><Eyebrow>Selected work</Eyebrow><h2>Built for real places.</h2></div><div className="filter-tabs">{(['All', 'Residential', 'Commercial'] as const).map(x => <button key={x} className={filter === x ? 'active' : ''} onClick={() => setFilter(x)}>{x}</button>)}</div></div></Reveal><div className="projects-grid">{projects.map((p, i) => <Reveal key={p.name}><article className={`project-card project-${i}`}><img src={p.image} alt={`${p.name}, ${p.type} solar project in ${p.location}`} /><div className="project-overlay"><span>{p.type}</span><h3>{p.name}</h3><p>{p.location} · {p.systemSize}</p></div></article></Reveal>)}</div></div></section> }

function SavingsSection() { return <section className="savings-section"><div className="container"><Reveal><Eyebrow light>Plan with perspective</Eyebrow><h2>Make energy work harder for you.</h2><p className="section-intro">Solar can change the relationship between your property and the grid. Every project is different, so we start with the real numbers.</p></Reveal><div className="savings-grid"><Reveal><div className="comparison"><div className="comparison-row"><span>Traditional energy</span><div><i className="bar traditional" /></div><b>100%</b></div><div className="comparison-row"><span>Solar energy</span><div><i className="bar solar" /></div><b>28%</b></div><small>Illustrative energy cost comparison</small></div></Reveal><div className="savings-stats">{[['$2,140', 'Estimated annual savings'], ['72%', 'Estimated energy offset'], ['25+', 'Estimated system life']].map(([value, label]) => <Reveal key={label}><div><strong>{value}</strong><span>{label}</span></div></Reveal>)}</div></div><div className="disclaimer">Figures shown are illustrative estimates only and are not a guarantee of savings, performance, or system life.</div><ButtonLink dark>Talk through your options</ButtonLink></div></section> }

function Testimonials() { const [current, setCurrent] = useState(0); const testimonial = companyConfig.testimonials[current]; useEffect(() => { const timer = window.setInterval(() => setCurrent(x => (x + 1) % companyConfig.testimonials.length), 7000); return () => window.clearInterval(timer) }, []); return <section className="section testimonial-section"><div className="container testimonial-layout"><Reveal><Eyebrow>Client perspective</Eyebrow><h2>Good energy feels personal.</h2><p className="lead">A project like this should feel as considered as the place it powers.</p><div className="testimonial-controls"><button aria-label="Previous testimonial" onClick={() => setCurrent((current - 1 + companyConfig.testimonials.length) % companyConfig.testimonials.length)}><ChevronLeft /></button><button aria-label="Next testimonial" onClick={() => setCurrent((current + 1) % companyConfig.testimonials.length)}><ChevronRight /></button></div></Reveal><Reveal><div className="quote-card"><div className="stars">★★★★★</div><blockquote>“{testimonial.quote}”</blockquote><div className="quote-author"><span>{testimonial.name}</span><small>{testimonial.location}</small></div><div className="dots">{companyConfig.testimonials.map((_, i) => <button key={i} aria-label={`Show testimonial ${i + 1}`} className={i === current ? 'active' : ''} onClick={() => setCurrent(i)} />)}</div></div></Reveal></div></section> }

function Financing() { return <section className="section section-alt"><div className="container"><Reveal><div className="section-heading"><div><Eyebrow>Flexible paths</Eyebrow><h2>There is more than one way forward.</h2></div><ButtonLink>Explore your options</ButtonLink></div></Reveal><div className="financing-grid">{[['01', 'Pay Upfront', 'A direct path to owning your system and planning for your energy future.'], ['02', 'Financing Options', 'Explore payment approaches that fit your project and priorities.'], ['03', 'Custom Solutions', 'Let’s shape a conversation around your property, goals, and timing.']].map(([number, title, text]) => <Reveal key={title}><div className="finance-card"><span>{number}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight /></div></Reveal>)}</div></div></section> }

function FAQ() { const [open, setOpen] = useState<number | null>(0); return <section id="faq" className="section faq-section"><div className="container faq-layout"><Reveal><Eyebrow>Questions, answered</Eyebrow><h2>Start with the basics.</h2><p className="lead">No jargon. No pressure. Just a clearer view of what solar could look like for you.</p><ButtonLink>Ask our team</ButtonLink></Reveal><Reveal><div className="faq-list">{companyConfig.faqs.map((faq, i) => <div className={`faq-item ${open === i ? 'open' : ''}`} key={faq.question}><button onClick={() => setOpen(open === i ? null : i)} aria-expanded={open === i}><span>{faq.question}</span>{open === i ? <Minus /> : <Plus />}</button>{open === i && <p>{faq.answer}</p>}</div>)}</div></Reveal></div></section> }

function ContactForm() { const [sent, setSent] = useState(false); return <section id="contact" className="contact-section"><div className="container contact-layout"><Reveal><Eyebrow light>Let’s talk energy</Eyebrow><h2>Ready to take control of your energy?</h2><p>Let’s find the right solar solution for your property.</p><div className="contact-aside"><span>Call us</span><strong>{companyConfig.phone}</strong><span>Email us</span><strong>{companyConfig.email}</strong></div></Reveal><Reveal><form className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true) }}>{sent ? <div className="success-state"><span><Check /></span><h3>Thank you for reaching out.</h3><p>Our team will be in touch soon to learn more about your property.</p><button type="button" onClick={() => setSent(false)}>Send another message</button></div> : <><div className="form-row"><label>First name<input required placeholder="First name" /></label><label>Last name<input required placeholder="Last name" /></label></div><div className="form-row"><label>Email<input required type="email" placeholder="you@example.com" /></label><label>Phone<input placeholder="[PHONE NUMBER]" /></label></div><div className="form-row"><label>City<input placeholder="City" /></label><label>Province<select defaultValue=""><option value="">Select province</option>{['Alberta','British Columbia','Manitoba','New Brunswick','Newfoundland and Labrador','Nova Scotia','Ontario','Prince Edward Island','Quebec','Saskatchewan'].map(x => <option key={x}>{x}</option>)}</select></label></div><div className="form-row"><label>Property type<select defaultValue=""><option value="">Select property type</option><option>Residential</option><option>Commercial</option></select></label><label>Average monthly bill<input type="number" placeholder="$ 250" /></label></div><label>Message<textarea rows={4} placeholder="Tell us a little about your property or goals" /></label><button className="button-link calculator-button">Request My Free Assessment <ArrowRight /></button></>}</form></Reveal></div></section> }

function Footer() { return <footer><div className="container footer-grid"><div><a className="brand footer-brand" href="#home"><span className="brand-mark"><Sun /></span><span>[COMPANY NAME]</span></a><p>{companyConfig.tagline}</p><div className="socials"><a href="#" aria-label="Facebook"><Globe2 /></a><a href="#" aria-label="Instagram"><MessageCircle /></a><a href="#" aria-label="LinkedIn"><Link2 /></a><a href="#" aria-label="YouTube"><Play /></a></div></div><div><h3>Solar solutions</h3><a href="#solutions">Residential Solar</a><a href="#solutions">Commercial Solar</a><a href="#solutions">Battery Storage</a><a href="#solutions">Service & Maintenance</a></div><div><h3>Company</h3><a href="#about">About Us</a><a href="#projects">Projects</a><a href="#faq">FAQs</a><a href="#contact">Contact</a></div><div><h3>Contact</h3><a href={`tel:${companyConfig.phone}`}>{companyConfig.phone}</a><a href={`mailto:${companyConfig.email}`}>{companyConfig.email}</a><span>{companyConfig.address}</span></div></div><div className="container footer-bottom"><span>© 2026 [COMPANY NAME]. All rights reserved.</span><span><a href="#">Privacy Policy</a><a href="#">Terms & Conditions</a></span></div></footer> }

export default function SolarSite() { useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible') }), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(el => observer.observe(el)); return () => observer.disconnect() }, []); return <><Navbar /><main><Hero /><TrustBar /><WhySolar /><Solutions /><HowItWorks /><CanadaSection /><Projects /><SavingsSection /><Testimonials /><Financing /><FAQ /><section className="final-cta" style={{ backgroundImage: `linear-gradient(90deg, rgba(14,26,43,.93), rgba(14,26,43,.3)), url(${ctaImage})` }}><div className="container"><Eyebrow light>Make the move</Eyebrow><h2>Ready to take control<br />of your energy?</h2><p>Let’s find the right solar solution for your property.</p><ButtonLink>Get a Free Solar Assessment</ButtonLink></div></section><ContactForm /></main><Footer /><a href="#contact" className="mobile-quote">Get a Free Quote <ArrowRight /></a></> }

function ArrowUpRight() { return <ArrowRight aria-hidden="true" /> }
